application: yt-dlp

version: 0-3
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /api/.*
  script: mainGAE.app
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: ssl
  version: latest
- name: jinja2
  version: "2.6"
